[tool.poetry]
name = "hermes"
version = "0.1.0"
description = ""
authors = ["Pablo-Olmos <pablolmos0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
langchain = "*"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
